### ISSUE TITLE
Error resolveJsonModule

### ISSUE THREAD

**Issue by ArtYa2010** [Sempai-07/Telegramsjs#2]
## Telegramsjs@1.0.0-beta.1

![Screenshot_20230615-183512-555](https://github.com/Sempai-07/Telegramsjs/assets/136732224/9a112457-fe5f-4fc2-b3e8-f24b46c03186)

**Comment by Sempai-07** [comment]
How strange it didn't sound right, but I've been fixing this error for the past two hours. 🙂
