### ISSUE TITLE
How to create button

### ISSUE THREAD

**Issue by relyaf** [Sempai-07/Telegramsjs#3]
~~guide is urgent~~

**Comment by Sempai-07** [comment]
I sincerely apologize that you are facing difficulties in creating buttons using our library or perhaps couldn't fully understand the documentation. In the coming month, we are planning to release an updated documentation that will thoroughly explain how to work with buttons and address such issues. In the meantime, I suggest you join our Discord server, where our community members will be more than happy to provide you with 100% assistance. 

Discord link: https://discord.gg/zmBHKxruc6
Markup docs: https://telegramsjs.surge.sh/classes/Markup.html
Action: https://telegramsjs.surge.sh/classes/TelegramBot.html#action

**Comment by Fllyer-dev** [comment]
Thank you bro💕

**Comment by Sempai-07** [comment]
## You've been waiting a long time 🧐
### Action
- http://docs-telegramsjs.surge.sh/TelegramBot/action.html
### Markup
- http://docs-telegramsjs.surge.sh/Markup.html
