### ISSUE TITLE
Enhancing Events

### ISSUE THREAD

**Issue by ZadManHegreat** [Sempai-07/Telegramsjs#5]
## Enhancing Events

I've recently embarked on development using your library. It's remarkable how frequently it receives updates and improvements. However, from my perspective, I'd like to suggest a more elegant solution for `TypeScript` developers – adopting an event system akin to what's found in `grammjs`.

## Illustrative Example:

```typescript
// Handling messages without captions
bot.on("message", (ctx) => {
  const caption: string | undefined = ctx.caption;
});

// Targeting messages specifically with captions
bot.on("message:caption", (ctx) => {
  const caption: string = ctx.caption;
});
```

This proposed enhancement would not only simplify the code but also align it better with modern `TypeScript` development practices.

**Comment by Sempai-07** [comment]
> ## Enhancing Events
> I've recently embarked on development using your library. It's remarkable how frequently it receives updates and improvements. However, from my perspective, I'd like to suggest a more elegant solution for `TypeScript` developers – adopting an event system akin to what's found in `grammjs`.
> 
> ## Illustrative Example:
> ```ts
> // Handling messages without captions
> bot.on("message", (ctx) => {
>   const caption: string | undefined = ctx.caption;
> });
> 
> // Targeting messages specifically with captions
> bot.on("message:caption", (ctx) => {
>   const caption: string = ctx.caption;
> });
> ```
> 
> This proposed enhancement would not only simplify the code but also align it better with modern `TypeScript` development practices.

Here are some outlines of how it will be implemented:
[Implementation 1](https://github.com/Sempai-07/Telegramsjs/blob/e2ebd950b8a23d9ced1a3c95ed11a6f09a77ae08/src/helpers/Combined.ts#L66)
[](https://github.com/Sempai-07/Telegramsjs/blob/e2ebd950b8a23d9ced1a3c95ed11a6f09a77ae08/src/helpers/Combined.ts#L101)

This is not everything since the development process is ongoing 🛠️

**Comment by Sempai-07** [comment]
https://github.com/Sempai-07/Telegramsjs/releases/tag/2.0.0
