### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by ZadManHegreat** [Sempai-07/Telegramsjs#6]
## Documentation Improvements

- It has been observed that all the examples in the documentation are provided in `JavaScript`, but there are no examples available for `TypeScript`. Why not include examples for both programming languages?
- Furthermore, an enhancement could involve the addition of a functions list on the right side for both mobile and desktop users.
- Additionally, it would be valuable to have a search functionality within the documentation to easily locate specific functions.
- It would also be possible to implement links to examples of bots, which could greatly assist users.

**Comment by Sempai-07** [comment]
Regarding the documentation, I'll mention one thing: it will be written using Docusaurus, but in the first week of the release of `telegramsjs@2.0.0`, I might not have time to create the documentation, so I will use Typedoc 📚🫡

> ## Documentation Improvements
> * It has been observed that all the examples in the documentation are provided in `JavaScript`, but there are no examples available for `TypeScript`. Why not include examples for both programming languages?
> * Furthermore, an enhancement could involve the addition of a functions list on the right side for both mobile and desktop users.
> * Additionally, it would be valuable to have a search functionality within the documentation to easily locate specific functions.
> * It would also be possible to implement links to examples of bots, which could greatly assist users.

Regarding the documentation, I'll mention one thing: it will be written using `docusaurus`, but in the first week of the release of `telegramsjs@2.0.0`, I might not have time to create the documentation, so I will use `typedoc` 📚🫡

**Comment by Sempai-07** [comment]
# Being finalized
https://telegramsjs-dev.surge.sh
