### ISSUE TITLE
Modifying the login Method

### ISSUE THREAD

**Issue by ZadManHegreat** [Sempai-07/Telegramsjs#7]
Modifying the `login` method is necessary because in the latest version of `telegramsjs@2.2.0`, a `disconnect` method has been added, which stops the reception of API requests. However, the current `login` method is unable to bring the bot back into operation after a disconnection. This is important because without this functionality, the bot won't be able to continue receiving updates after a connection is lost. Modifying the `login` method allows the bot to automatically reconnect and ensures uninterrupted operation.

**Comment by Sempai-07** [comment]
[Added 2.3.0](https://github.com/Sempai-07/Telegramsjs/commit/357d5f4f783482775af846dc926def19e0c6dbbd). Thank you
